export const ICON_WIDTH = 8;
export const ICON_HEIGHT = 8;
export const MAP_URL = "/mc-assets/map_icons.png";

export enum Icons {
  WHITE_ARROW = 0,
  GREEN_ARROW = 1,
  RED_ARROW = 2,
  BLUE_ARROW = 3,
  WHITE_CROSS = 4,
  RED_POINTER = 5,
  WHITE_CIRCLE = 6,
  SMALL_WHITE_CIRCLE = 7,
  MANSION = 8,
  TEMPLE = 9,
  WHITE_BANNER = 10,
  ORANGE_BANNER = 11,
  MAGENTA_BANNER = 12,
  LIGHT_BLUE_BANNER = 13,
  YELLOW_BANNER = 14,
  LIME_BANNER = 15,
  PINK_BANNER = 16,
  GRAY_BANNER = 17,
  LIGHT_GRAY_BANNER = 18,
  CYAN_BANNER = 19,
  PURPLE_BANNER = 20,
  BLUE_BANNER = 21,
  BROWN_BANNER = 22,
  GREEN_BANNER = 23,
  RED_BANNER = 24,
  BLACK_BANNER = 25,
  TEASURE_MARKER = 26,
}

export const ICON_COORDS_MAPPING: {[key: number]: [number, number]} = {
  [Icons.WHITE_ARROW]: [0, 0],
  [Icons.GREEN_ARROW]: [1, 0],
  [Icons.RED_ARROW]: [2, 0],
  [Icons.BLUE_ARROW]: [3, 0],
  [Icons.WHITE_CROSS]: [4, 0],
  [Icons.RED_POINTER]: [5, 0],
  [Icons.WHITE_CIRCLE]: [6, 0],
  [Icons.SMALL_WHITE_CIRCLE]: [7, 0],
  [Icons.MANSION]: [8, 0],
  [Icons.TEMPLE]: [9, 0],
  [Icons.WHITE_BANNER]: [10, 0],
  [Icons.ORANGE_BANNER]: [11, 0],
  [Icons.MAGENTA_BANNER]: [12, 0],
  [Icons.LIGHT_BLUE_BANNER]: [13, 0],
  [Icons.YELLOW_BANNER]: [14, 0],
  [Icons.LIME_BANNER]: [15, 0],
  [Icons.PINK_BANNER]: [0, 1],
  [Icons.GRAY_BANNER]: [1, 1],
  [Icons.LIGHT_GRAY_BANNER]: [2, 1],
  [Icons.CYAN_BANNER]: [3, 1],
  [Icons.PURPLE_BANNER]: [4, 1],
  [Icons.BLUE_BANNER]: [5, 1],
  [Icons.BROWN_BANNER]: [6, 1],
  [Icons.GREEN_BANNER]: [7, 1],
  [Icons.RED_BANNER]: [8, 1],
  [Icons.BLACK_BANNER]: [9, 1],
  [Icons.TEASURE_MARKER]: [10, 1],
}
